version: '3.8'

services:
  backend:
    build: .
    container_name: nodejs-app
    volumes:
      - :/usr/src/app
      - /user/src/app/node_modules
    ports:
      - 5000:5000
    command: npx nodemon server.js
